// EP-19 · The complete pilot journey, in a real browser, against the real API, worker and database.
//
// WHAT THIS PROVES that no in-process test can: that the screens a pilot actually touches reach a
// governed server finding, and that the figure on the final screen is the SERVER's number rather
// than something the browser worked out for itself. Those two claims are the product.
//
// Three things make this harness different from `e2e/smoke.mjs`:
//
//   1. It uses the Vite DEV server, not `vite preview`. `apiClient.ts` attaches development identity
//      headers only when `import.meta.env.DEV`, so against a production build every governed call
//      would arrive unauthenticated and 401. A preview-based harness could not reach the API at all.
//   2. It starts a real Fastify process with a real worker loop over a real PostgreSQL database.
//   3. The two governance halves are performed by two DIFFERENT identities, because the server
//      refuses them from one — which is the point of the separation, not a detail of the screen.
//
// Deterministic: a fixed synthetic CSV, a fixed as-of date, a boundary derived once per run.
// Exits non-zero on any failure. Never uses real or disguised customer data.
import { chromium } from "playwright";
import { spawn } from "node:child_process";
import { existsSync, readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve, join } from "node:path";
import { createHash, randomUUID } from "node:crypto";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const API_PORT = Number(process.env.JOURNEY_API_PORT ?? 4000);
const UI_PORT = Number(process.env.JOURNEY_UI_PORT ?? 5199);
const UI_BASE = `http://127.0.0.1:${UI_PORT}/`;
const CHROMIUM = "/opt/pw-browsers/chromium";
const executablePath = existsSync(CHROMIUM) ? CHROMIUM : undefined;

if (!process.env.DATABASE_URL) {
  console.error("DATABASE_URL is required — this harness runs against a real database on purpose.");
  process.exit(2);
}

// One boundary per run. The worker polls a fixed boundary list, so it has to be known before the
// server starts; deriving it here (rather than hardcoding) keeps repeat runs from colliding.
const BOUNDARY = `journey-${randomUUID().slice(0, 8)}`;
const POLICY_ID = `journey-bar-${randomUUID().slice(0, 8)}`;
const POLICY_VERSION = "1.0.0";
const AS_OF = "2026-03-01";

const results = [];
let failures = 0;
let halted = null;
function check(name, ok, detail = "") {
  results.push({ name, ok });
  if (!ok) failures += 1;
  console.log(`${ok ? "PASS" : "FAIL"} · ${name}${detail ? ` · ${detail}` : ""}`);
}
function checkEqual(name, actual, expected) {
  check(name, actual === expected, actual === expected ? "" : `expected ${expected}, got ${actual}`);
}

// ── Structural unreachability ──────────────────────────────────────────────────────────────────────
// A stage can depend on a condition that, if unmet, makes every later step STRUCTURALLY unreachable —
// not merely likely to fail. `Pilot readiness →` is the case in hand: with no ACTIVE admission bar the
// server answers NOT_ASSESSABLE, the gate blocks, and the button is never rendered, so clicking it can
// only spend its 30s timeout and die. NC-17 — activation rewired to an identity lacking
// `ActivatePilotPolicy` — lands exactly there: it recorded its intended authorization failures and then
// fell into a bare `locator.click: Timeout 30000ms exceeded`, an abort with no stated reason.
//
// `haltIf` ends the run at that point, deliberately, with the reason printed. Three properties make it
// a termination rather than a way to go quiet:
//
//   * it is NOT a catch — it swallows no error and suppresses no failure;
//   * it passes nothing. The unreached checks are reported as unreached, never as passes;
//   * it CANNOT fire on a healthy journey. It refuses to halt unless a check has already been
//     recorded as failed, so the cause is on the record before the stop — and a halt requested with
//     a clean record is itself recorded as a failure of this harness.
class JourneyHalted extends Error {
  constructor(reason) {
    super(reason);
    this.name = "JourneyHalted";
  }
}
function haltIf(unreachable, reason) {
  if (!unreachable) return;
  if (failures === 0) {
    check(`the harness halted with no recorded failure to justify it — ${reason}`, false);
  }
  throw new JourneyHalted(reason);
}

// ── Fixture ────────────────────────────────────────────────────────────────────────────────────────
// Generated by the repository's own deterministic generator, so the browser journey and the server
// matrix are exercising the same bytes. Written to a temp file because the screen takes a file pick.
// `npm run test:journey` writes these first, via `scripts/write-journey-fixture.ts`, so the bytes
// come from the same generator the server matrix uses rather than a copy pasted in here.
const CSV_PATH = join(ROOT, "e2e/fixtures/journey.synthetic.csv");
// A SECOND dataset for the frozen-policy section, from the same generator at a different size.
// EP-23 claimed this was forced by the duplicate rule; section 10 shows it was not, because the
// idempotency key includes the dataset LABEL and the frozen section supplies a fresh one. It stays
// because distinct bytes leave no reading under which section 11 could be observing a duplicate.
const FROZEN_CSV_PATH = join(ROOT, "e2e/fixtures/journey.frozen.synthetic.csv");
// The bytes the repeats section re-uploads. It is CSV_PATH — the whole point is that they are the SAME
// bytes the server already accepted — and it exists as its own name only so NC-26 can point it at a
// different file and demonstrate that the section's claim really rests on exact-byte identity rather
// than on "uploading a similar CSV". A harness that cannot be made to fail is not evidence.
const REPEAT_CSV_PATH = CSV_PATH;
// The dataset label the first upload uses, reused verbatim by the repeat. It has to be a known value
// rather than a fresh uuid, because the idempotency identity is derived from
// (boundaryId, datasetId, sha256(csvText)) — the LABEL is part of it. See section 10.
const JOURNEY_DATASET_LABEL = `journey-${randomUUID().slice(0, 8)}`;
for (const path of [CSV_PATH, FROZEN_CSV_PATH]) {
  if (!existsSync(path)) {
    console.error("missing journey fixture — run `npm run fixture:journey` first (test:journey does).");
    process.exit(2);
  }
}
const { policy: SCENARIO_POLICY, scenarios: RISK_SCENARIOS } = JSON.parse(
  readFileSync(join(ROOT, "e2e/fixtures/journey.fixture.json"), "utf8"),
);

// ── Processes ──────────────────────────────────────────────────────────────────────────────────────
function startProcess(label, command, args, env) {
  const child = spawn(command, args, {
    cwd: ROOT,
    detached: true,
    env: { ...process.env, ...env },
    stdio: ["ignore", "pipe", "pipe"],
  });
  child.stdout.on("data", (b) => process.env.JOURNEY_VERBOSE && console.log(`[${label}] ${b}`));
  child.stderr.on("data", (b) => console.error(`[${label}] ${b}`));
  return child;
}

function startApi() {
  return startProcess("api", process.execPath, [resolve(ROOT, "node_modules/.bin/vite-node"), "server/index.ts"], {
    PORT: String(API_PORT),
    HOST: "127.0.0.1",
    // The worker must be running for an execution to leave `queued`.
    NH_AGENTS_ENABLED: "true",
    NH_AGENT_BOUNDARIES: BOUNDARY,
    NH_AGENT_IDLE_DELAY_MS: "200",
    // EP-18: the assessment agent publishes no candidates, so it needs no admission-policy registry.
    // Supplying a fabricated RecoveryType:threshold pair here would put an invented number into the
    // configuration of a test whose whole subject is not inventing numbers.
    NH_PILOT_ASSESSMENT_AGENT_ENABLED: "true",
    NH_PILOT_INPUT_TERMINAL_GRACE_HOURS: "24",
    NH_PILOT_INPUT_ABANDONED_RETENTION_DAYS: "7",
  });
}

function startUi() {
  return startProcess("ui", process.execPath, [
    resolve(ROOT, "node_modules/vite/bin/vite.js"),
    "--port", String(UI_PORT), "--strictPort", "--host", "127.0.0.1",
  ], { API_PORT: String(API_PORT) });
}

async function waitFor(label, probe, timeoutMs = 60_000) {
  const deadline = Date.now() + timeoutMs;
  let last = "";
  while (Date.now() < deadline) {
    try {
      if (await probe()) return;
    } catch (e) {
      last = e instanceof Error ? e.message : String(e);
    }
    await new Promise((r) => setTimeout(r, 400));
  }
  throw new Error(`${label} did not become reachable within ${timeoutMs}ms${last ? ` (${last})` : ""}`);
}

function stop(child) {
  if (!child?.pid) return;
  try { process.kill(-child.pid, "SIGTERM"); } catch { /* already gone */ }
}

// ── The journey ────────────────────────────────────────────────────────────────────────────────────
let api, ui, browser;
try {
  api = startApi();
  ui = startUi();
  await waitFor("api", async () => (await fetch(`http://127.0.0.1:${API_PORT}/health`)).ok);
  await waitFor("ui", async () => (await fetch(UI_BASE)).ok);

  browser = await chromium.launch({ executablePath });
  const context = await browser.newContext();
  const page = await context.newPage();

  // Every request the page makes, so "no external egress" is a measured claim, not an assumption.
  const requested = [];
  page.on("request", (r) => requested.push(r.url()));
  const pageErrors = [];
  page.on("pageerror", (e) => pageErrors.push(e.message));

  await page.goto(UI_BASE, { waitUntil: "domcontentloaded" });

  // ── 1 · Governance: the operator proposes the bar ────────────────────────────────────────────────
  await page.getByRole("button", { name: "Pilot Policy Governance" }).click();
  await page.getByLabel("Boundary (tenant)").fill(BOUNDARY);
  await page.getByLabel("Policy id").fill(POLICY_ID);
  await page.getByLabel("Policy version").fill(POLICY_VERSION);
  for (const [label, value] of [
    ["Min accepted rows", String(SCENARIO_POLICY.minAcceptedRows)],
    ["Min distinct entities", String(SCENARIO_POLICY.minDistinctEntities)],
    ["Min coverage (days)", String(SCENARIO_POLICY.minCoverageDays)],
    ["Max missing recommended cols", String(SCENARIO_POLICY.maxMissingRecommendedColumns)],
    ["Max rejection rate", String(SCENARIO_POLICY.maxRejectionRate)],
    ["Max single-reason share", String(SCENARIO_POLICY.maxSingleReasonShare)],
    ["Max duplicate rate", String(SCENARIO_POLICY.maxDuplicateRate)],
    ["Max ordering-defect rate", String(SCENARIO_POLICY.maxOrderingDefectRate)],
  ]) {
    await page.getByLabel(label, { exact: true }).fill(value);
  }
  // The review gate first: the three state boxes are disabled until it is ticked, so an untouched form
  // cannot half-state a policy.
  await page.getByLabel("I have reviewed lifecycle coverage").check();
  for (const state of SCENARIO_POLICY.requiredLifecycleStates) {
    await page.getByRole("group", { name: "Required lifecycle states" }).getByLabel(state, { exact: true }).check();
  }
  await page.getByLabel("Require provenance declaration").selectOption(String(SCENARIO_POLICY.requireProvenanceDeclaration));
  await page.getByLabel("Rationale (required on every act)").fill("journey fixture bar");

  const proposeButton = page.getByRole("button", { name: /^Propose as / });
  const activateButton = page.getByRole("button", { name: /^Activate as / });

  // An out-of-range threshold must NAME the field. A silently disabled button sends an operator hunting
  // through eight boxes, and `validateAdmissionPolicy` already returns the field and the reason.
  await page.getByLabel("Max duplicate rate", { exact: true }).fill("1.1");
  const defect = page.getByLabel("Policy threshold errors").getByText(/maxDuplicateRate:.*between 0 and 1/);
  // waitFor before sampling: isVisible() reads the DOM as it is right now, so a check that ran before
  // React flushed would report the defect list missing when it had merely not rendered yet. A false
  // FAIL here is noise; the same race in the other direction is how a real gap gets a green tick.
  await defect.waitFor({ state: "visible", timeout: 10_000 }).catch(() => undefined);
  check("an invalid threshold names the field and blocks proposal",
    (await defect.isVisible()) && !(await proposeButton.isEnabled()));
  await page.getByLabel("Max duplicate rate", { exact: true }).fill(String(SCENARIO_POLICY.maxDuplicateRate));
  const proposerName = (await proposeButton.textContent())?.replace("Propose as ", "").trim() ?? "";
  const stewardName = (await activateButton.textContent())?.replace("Activate as ", "").trim() ?? "";
  check(
    "the two governance acts are offered as two different identities",
    proposerName !== "" && stewardName !== "" && proposerName !== stewardName,
    `${proposerName} vs ${stewardName}`,
  );

  await proposeButton.click();
  // The state pill and the "judges nothing" verdict are BOTH rendered from the lifecycle read that
  // `act` performs after the write — a read that needs `AuditRead`. So the wait degrades instead of
  // throwing: if the read is refused, this must be a RECORDED failure attributable to this check, not
  // a harness abort that ends the run with nothing said about anything downstream (the NC-7 lesson).
  await page.getByText("DRAFT", { exact: true }).waitFor({ timeout: 15_000 }).catch(() => undefined);
  check("a proposed bar is DRAFT and judges nothing",
    (await page.getByText("DRAFT", { exact: true }).isVisible()) &&
    (await page.getByText("judges nothing").isVisible()));

  // ── 2 · Governance: a DIFFERENT identity puts it in force ────────────────────────────────────────
  await activateButton.click();
  await page.getByText("ACTIVE", { exact: true }).waitFor({ timeout: 15_000 }).catch(() => undefined);
  check("an activated bar may judge a dataset",
    (await page.getByText("ACTIVE", { exact: true }).isVisible()) &&
    (await page.getByText("may judge a dataset").isVisible()));

  // A lifecycle belongs to one exact boundary, policy id and version. Editing any of them must
  // immediately hide the old ACTIVE verdict — the state, the "may judge" pill and the hash together.
  const policyIdInput = page.getByLabel("Policy id", { exact: true });
  await policyIdInput.fill(`${POLICY_ID}-other`);
  check("changing policy identity hides the old ACTIVE verdict",
    (await page.getByText("not proposed", { exact: true }).isVisible()) &&
    !(await page.getByText("may judge a dataset").count()) &&
    !(await page.getByText("Policy hash", { exact: false }).count()));
  // Restoring the identity does NOT restore the verdict: it has to be read again, deliberately.
  await policyIdInput.fill(POLICY_ID);
  check("restoring the identity still requires an explicit re-read",
    await page.getByText("not proposed", { exact: true }).isVisible());
  await page.getByRole("button", { name: "Read lifecycle" }).click();
  await page.getByText("ACTIVE", { exact: true }).waitFor({ timeout: 15_000 }).catch(() => undefined);
  check("an explicit re-read restores the ACTIVE verdict for the selected identity",
    (await page.getByText("ACTIVE", { exact: true }).isVisible()) &&
    (await page.getByText("may judge a dataset").isVisible()));

  // SEPARATION OF DUTIES, read out of the SERVER's audit trail — not off the buttons.
  //
  // This check used to be `page.locator("main").innerText()` containing both identity strings. The
  // Propose and Activate buttons are in `main` and render those exact strings, so it passed on the
  // labels alone: suppressing the entire audit panel left it green and the journey at 61/61. It was
  // the assertion claiming to prove two-actor governance, and it proved nothing.
  //
  // Everything below is scoped to the audit panel, which the screen renders ONLY from a successful
  // lifecycle read — and that read requires `AuditRead`, which the operator does not hold. So the
  // panel's mere existence is evidence the UI performed it as a steward.
  const bareId = (label) => label.replace(/\s*\(.*\)$/, "").trim();
  const audit = page.getByText("Who decided what", { exact: false }).locator("..");
  await audit.waitFor({ state: "visible", timeout: 15_000 }).catch(() => undefined);
  check("the governance audit trail loaded, which requires an AuditRead identity",
    await audit.isVisible());

  // Degrade to empty rather than throwing: if the panel is absent the two checks below must be
  // RECORDED failures, not a harness abort that stops the run and reports nothing (the NC-7 lesson).
  const auditText = ((await audit.innerText().catch(() => "")) || "").replace(/\s+/g, " ");
  check("the audit trail records both transitions, each attributed to its own actor",
    auditText.includes("PROPOSED") && auditText.includes("ACTIVATED") &&
    auditText.includes(bareId(proposerName)) && auditText.includes(bareId(stewardName)),
    auditText.slice(0, 200));

  // Rendered from the server's own proposedBy/activatedBy comparison, so it cannot be satisfied by a
  // label. The negative sentence is asserted absent too: the screen says outright when one identity
  // did both, and that wording appearing here would mean the server allowed what it must refuse.
  check("the server recorded two DIFFERENT identities for the two governance acts",
    auditText.includes("two different identities, which is the point.") &&
    !auditText.includes("the same identity, which the server should not have allowed."));

  // ── 3 · Assessment: intake and admission ────────────────────────────────────────────────────────
  await page.getByRole("button", { name: "Revenue Opportunity Assessment" }).click();
  await page.getByLabel("Admission policy id").fill(POLICY_ID);
  await page.getByLabel("Admission policy version").fill(POLICY_VERSION);
  await page.getByLabel("Analysis as-of date").fill(AS_OF);
  await page.getByLabel("Pilot boundary").fill(BOUNDARY);
  await page.getByLabel("Dataset label").fill(JOURNEY_DATASET_LABEL);
  await page.getByLabel("Contract system of record").fill("synthetic-crm");
  await page.getByLabel("Billing system of record").fill("synthetic-billing");
  await page.getByLabel("Product/telemetry source").fill("synthetic-telemetry");
  await page.getByLabel("Data owner (role, not a person)").fill("synthetic-revenue-operations");
  await page.getByLabel("Extraction method").fill("synthetic deterministic generator");
  await page.getByLabel("Extracted at (UTC)").fill("2026-03-01T00:00:00.000Z");
  await page.getByLabel("Coverage start").fill("2026-01-01");
  await page.getByLabel("Coverage end").fill("2026-03-31");

  // The server's own receipt for this submission, kept for the repeat section below: its
  // `idempotencyKey` is what the repeat has to collide with. Captured here rather than reconstructed,
  // because a key the harness derived itself would prove only that the harness can hash.
  const firstIntake = page.waitForResponse(
    (r) => r.url().includes("/api/pilot/datasets") && r.request().method() === "POST",
    { timeout: 30_000 },
  );
  await page.setInputFiles('input[type="file"]', CSV_PATH);
  const firstIntakeBody = await firstIntake
    .then((r) => (r.ok() ? r.json() : null))
    .catch(() => null);

  // Admitted ⇒ the flow leaves Upload on its own. Before EP-19 it could not, because the UI never
  // sent an admission policy id and the server therefore always answered NOT_ASSESSABLE.
  // `check(..., true)` used to stand here, with the bare `waitFor` above as the only real gate. That
  // records a PASS for a condition it never sampled, and if the wait ever throws the run aborts with
  // this check never reported at all. Both halves are now the assertion.
  const readiness = page.getByRole("button", { name: "Pilot readiness →" });
  await readiness.waitFor({ timeout: 30_000 }).catch(() => undefined);
  const admitted = await readiness.isVisible();
  check("an admitted dataset leaves the upload screen", admitted);
  // The gate between "a dataset was admitted" and everything that inspects a run. Sections 4-10 read
  // a cohort, a preview, an execution and a ledger that only exist downstream of an admitted dataset,
  // and the first of them clicks this very button. Without it there is nothing to assert against and
  // no way to reach the assertions, so the journey stops here with the cause already recorded above.
  haltIf(!admitted, "no dataset was admitted, so the cohort, preview, governed execution and ledger " +
    "steps have no run to inspect and the button that opens them is not on the page");

  // ── 4 · The browser's own figure is reachable, and is labelled a preview ─────────────────────────
  await readiness.click();
  await page.getByRole("button", { name: "Observed result →" }).click();
  const previewText = await page.locator("main").innerText();
  check(
    "the browser figure says it was computed in this browser",
    /local preview/i.test(previewText) && /in this browser/i.test(previewText),
  );
  check(
    "the browser figure denies being an execution, a Proof or Revenue Returned",
    /not an execution, a Proof, or Revenue Returned/i.test(previewText.replace(/\s+/g, " ")),
  );

  // ── 5 · The governed execution ───────────────────────────────────────────────────────────────────
  await page.getByRole("button", { name: "Run governed execution" }).click();

  // `completed` is the only acceptable end. A timeout here is a failure of the journey, not a pass:
  // the screen is required to show a timeout as a timeout, and this harness is required to fail.
  // The execution-state pill, specifically — the event log below it also contains the word, and
  // matching either would let a COMPLETED event on a run that is still settling read as a result.
  // Degrading rather than throwing so that a refused or stalled execution is reported by the NAMED
  // check below — a harness abort here would end the run with the execution checks never printed, and
  // an authorization defect in the intake path would look like a broken harness instead of a failure.
  await page.getByText("Completed — an observation was recorded")
    .waitFor({ timeout: 90_000 }).catch(() => undefined);
  // Scoped to <main>, NOT the whole body. The sidebar carries a standing "Auditable recovered"
  // total for the separate proven ledger — that belongs there, and matching it would turn correct
  // two-ledger chrome into a false failure while hiding a real one in the noise.
  const executionText = (await page.locator("main").innerText()).replace(/\s+/g, " ");
  check(
    "the governed execution reached a server-reported completion",
    /Completed — an observation was recorded/.test(executionText),
  );

  // ── 6 · The displayed figures are the SERVER's, not the browser's ────────────────────────────────
  const proposerId = proposerName.replace(/\s*\(.*\)$/, "").trim();
  const listed = await page.evaluate(async ([boundaryId, actorId]) => {
    const res = await fetch(`/api/pilot/assessments?boundaryId=${encodeURIComponent(boundaryId)}`, {
      headers: { "x-actor-id": actorId, "x-actor-role": "operator" },
    });
    // Surfaced rather than swallowed: an unauthorised read must not be indistinguishable from a
    // boundary that genuinely holds no execution.
    return { status: res.status, body: res.ok ? await res.json() : await res.text() };
  }, [BOUNDARY, proposerId]);
  checkEqual("the execution list is readable by the acting operator", listed.status, 200);
  // The endpoint returns a bare array, not a wrapper object.
  const executions = Array.isArray(listed.body) ? listed.body : [];
  const executionId = executions[0]?.executionId ?? null;
  check("exactly one execution exists for this boundary", executions.length === 1,
    `status=${listed.status} count=${executions.length}`);

  const apiView = executionId
    ? await page.evaluate(async ([boundaryId, id, actorId]) => {
        const res = await fetch(
          `/api/pilot/assessments/${id}?boundaryId=${encodeURIComponent(boundaryId)}`,
          { headers: { "x-actor-id": actorId, "x-actor-role": "operator" } },
        );
        return res.ok ? res.json() : null;
      }, [BOUNDARY, executionId, proposerId])
    : null;

  checkEqual("the API agrees the execution completed", apiView?.state, "completed");
  const finding = apiView?.finding?.finding ?? null;
  check("the API produced a finding", finding !== null);
  if (finding) {
    // The load-bearing comparison of the whole harness: the number on the screen is the number the
    // server computed. A browser-side figure that merely happened to look plausible would fail here.
    check(
      `the screen shows the server's cycle count (${finding.acceptedCycleCount})`,
      executionText.includes(String(finding.acceptedCycleCount)),
    );
    const minorToText = (minor) =>
      (minor / 100).toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 });
    check(
      `the screen shows the server's observed unpaid amount (${minorToText(finding.observedUnpaidMinor)})`,
      executionText.includes(minorToText(finding.observedUnpaidMinor)),
    );
    check("the execution is bound to an admission decision", Boolean(apiView.binding?.admissionDecisionId));
  }

  // ── 7 · Nothing on the result claims proven money ────────────────────────────────────────────────
  //
  // Banning the words outright would be the wrong test: this panel SHOULD say "no dollar here has
  // been recovered, proven, or counted", and a check that failed on that would push the honest
  // sentence off the screen. So the rule is the repository's existing one for retracted claims —
  // the proven-ledger vocabulary may appear only inside a denial of itself.
  const NEGATION = /\b(no|not|never|nothing|without)\b/i;
  for (const term of ["Revenue Returned", "Auditable", "recovered", "proven"]) {
    const pattern = new RegExp(`(.{0,60})\\b${term}\\b`, "gi");
    const claims = [];
    for (const match of executionText.matchAll(pattern)) {
      if (!NEGATION.test(match[1] ?? "")) claims.push(`…${match[1]}${term}`);
    }
    check(
      `the governed result mentions "${term}" only to deny it`,
      claims.length === 0,
      claims.slice(0, 2).join(" | "),
    );
  }
  // And the denial must actually be present, not merely un-contradicted: an empty panel would pass
  // every check above while telling the reader nothing about what the figure is not.
  check(
    "the governed result states plainly that nothing here was recovered, proven or counted",
    /no dollar here has been recovered, proven, or counted/i.test(executionText),
  );
  check(
    "the governed result names itself Revenue Opportunity",
    /Revenue Opportunity/i.test(executionText),
  );

  // ── 8 · Each generated data-risk scenario, through the actual upload screen ────────────────────
  // The API/worker matrix checks the domain decision. These checks also catch a browser that shows
  // a misleading verdict, promotes a preflight refusal to a server verdict, or lets a refused
  // dataset leave Upload. Each file gets a fresh screen and dataset id; all share the activated bar.
  /**
   * What the report panel SHOWS, asserted identically whether the dataset was admitted or refused.
   *
   * One helper rather than two copies: a dataset can be correctly admitted by the server and still be
   * displayed with the wrong counts, or with a rejected row's code silently dropped. That is the class
   * of defect only a browser can see, and it is no less serious on the admitted path.
   */
  /**
   * The number a Counter shows, compared EXACTLY.
   *
   * Not `endsWith`: a counter displaying 31 where 1 is expected ends with "1" and would pass. NC-12
   * caught that — sabotaging the panel to show `dataRows` left `one-valid-row` green, because its
   * expected accepted count is 1 and the wrong value was 31. The value is the counter's last token,
   * with the thousands separator `toLocaleString` adds removed.
   */
  function counterValue(text) {
    const last = text.trim().split(/\s+/).pop() ?? "";
    return Number(last.replace(/,/g, ""));
  }

  async function checkVisibleReport(scenario) {
    const report = page.locator("main");
    const accepted = await page.getByText("Accepted", { exact: true }).locator("..").innerText();
    const rejected = await page.getByText("Rejected", { exact: true }).locator("..").innerText();
    check(`${scenario.id}: the visible accepted/rejected counts match the fixture`,
      counterValue(accepted) === scenario.expected.acceptedRows &&
      counterValue(rejected) === scenario.expected.rejectedRows,
      `accepted=${counterValue(accepted)} rejected=${counterValue(rejected)} ` +
      `expected ${scenario.expected.acceptedRows}/${scenario.expected.rejectedRows}`);
    for (const code of scenario.expected.codes) {
      check(`${scenario.id}: the report names ${code}`,
        (await report.getByText(code, { exact: true }).count()) > 0);
    }
  }

  /**
   * A fresh assessment screen with the provenance declaration filled in.
   *
   * Extracted because the frozen-policy section below needs the identical thirteen fields: two copies
   * would drift, and a drifted copy is how a section ends up asserting against a form the product no
   * longer has. `page.goto` first — navigating away unmounts `Assessment` (App.tsx renders screens
   * conditionally), so every upload genuinely starts from an empty screen.
   */
  async function openIntakeScreen(datasetLabel) {
    await page.goto(UI_BASE, { waitUntil: "domcontentloaded" });
    await page.getByRole("button", { name: "Revenue Opportunity Assessment" }).click();
    await page.getByLabel("Admission policy id").fill(POLICY_ID);
    await page.getByLabel("Admission policy version").fill(POLICY_VERSION);
    await page.getByLabel("Analysis as-of date").fill(AS_OF);
    await page.getByLabel("Pilot boundary").fill(BOUNDARY);
    await page.getByLabel("Dataset label").fill(datasetLabel);
    await page.getByLabel("Contract system of record").fill("synthetic-crm");
    await page.getByLabel("Billing system of record").fill("synthetic-billing");
    await page.getByLabel("Product/telemetry source").fill("synthetic-telemetry");
    await page.getByLabel("Data owner (role, not a person)").fill("synthetic-revenue-operations");
    await page.getByLabel("Extraction method").fill("synthetic deterministic generator");
    await page.getByLabel("Extracted at (UTC)").fill("2026-03-01T00:00:00.000Z");
    await page.getByLabel("Coverage start").fill("2026-01-01");
    await page.getByLabel("Coverage end").fill("2026-03-31");
  }

  for (const scenario of RISK_SCENARIOS) {
    await openIntakeScreen(`matrix-${scenario.id}-${randomUUID().slice(0, 8)}`);

    const serverReply = scenario.expected.usableForAssessment
      ? page.waitForResponse(
          (r) => r.url().includes("/api/pilot/datasets") && r.request().method() === "POST",
          { timeout: 30_000 },
        )
      : null;
    await page.setInputFiles('input[type="file"]', {
      name: `${scenario.id}.synthetic.csv`, mimeType: "text/csv",
      buffer: Buffer.from(scenario.csvText, "utf8"),
    });

    if (scenario.expected.admission === "ADMISSIBLE") {
      await page.getByRole("button", { name: "Pilot readiness →" }).waitFor({ timeout: 30_000 });
      const reply = await serverReply;
      const body = reply?.ok() ? await reply.json() : null;
      check(`${scenario.id}: admitted by the server and progressed in the browser`,
        body?.admission?.outcome === "ADMISSIBLE" &&
        body.counts?.acceptedRows === scenario.expected.acceptedRows &&
        body.counts?.rejectedRows === scenario.expected.rejectedRows);

      // The report panel is NOT on screen here: progressing moved the flow to the cohort step, which
      // unmounts it. `validation` survives that move (it is cleared only by the next upload), so going
      // back to Upload re-renders the panel with the SERVER result — deterministically, no race.
      await page.getByRole("button", { name: "← Upload" }).click();
      await page.getByText("Data contract validation", { exact: true }).waitFor({ timeout: 30_000 });
      check(`${scenario.id}: the admitted report is marked server-verified`,
        (await page.locator("main").innerText()).includes("server-verified"));
      await checkVisibleReport(scenario);
    } else {
      await page.getByText("Data contract validation", { exact: true }).waitFor({ timeout: 30_000 });
      const preliminary = !scenario.expected.usableForAssessment;
      if (preliminary) {
        // Preflight knows no active bar; "no policy configured" would misdescribe an activated bar as
        // missing. It reports contract usability only and makes no policy fitness claim.
        await page.getByText("pilot admission not evaluated", { exact: true }).waitFor({ timeout: 30_000 });
        check(`${scenario.id}: preflight makes no policy fitness claim`,
          (await page.locator("main").innerText()).includes("No admission policy was read here") &&
          (await page.getByText("Pilot admission", { exact: true }).count()) === 0);
      } else {
        const admissionPill = page.getByText("Pilot admission", { exact: true }).locator("..");
        await admissionPill.getByText(scenario.expected.admission.replace(/_/g, " ").toLowerCase(),
          { exact: true }).waitFor({ timeout: 30_000 });
      }
      const reply = await serverReply;
      if (!preliminary && !reply) throw new Error(`${scenario.id}: expected server verdict, got no response`);
      // An unusable file stops at local preflight and is labelled as such; a usable but unfit file
      // must receive an authoritative server verdict. Neither may expose the next-step button.
      const report = page.locator("main");
      const text = await report.innerText();
      check(`${scenario.id}: refusal has the correct authority and remains on Upload`,
        text.includes(preliminary ? "preview — not yet confirmed by the server" : "server-verified") &&
        (await page.getByRole("button", { name: "Pilot readiness →" }).count()) === 0);
      await checkVisibleReport(scenario);
      if (reply) {
        const body = await reply.json();
        check(`${scenario.id}: browser refusal agrees with the server`,
          body.admission?.outcome === scenario.expected.admission &&
          body.counts?.acceptedRows === scenario.expected.acceptedRows &&
          body.counts?.rejectedRows === scenario.expected.rejectedRows);
      }
    }
  }

  // ── 9 · A transport failure cannot turn a previous server verdict into permission ───────────────
  // The last matrix case leaves Upload visible. It may still carry an earlier server validation, so
  // interrupting the next submission tests both the error path and stale-verdict clearing.
  // PRECONDITION, asserted rather than assumed. The clearing check below is `count === 0`, which
  // passes trivially if the panel was never there. It IS there today — the last matrix scenario is an
  // admitted one, so the loop returned to Upload with a server-verified report — but that is incidental
  // to the scenario order, not a rule. Without this, reordering the matrix would leave the check green
  // and testing nothing, the same way `endsWith` did before NC-12.
  check("the upload screen still carries the previous server verdict before the failure",
    (await page.locator("main").getByText("server-verified").count()) > 0);

  await page.route("**/api/pilot/datasets", (route) => route.abort("failed"));
  await page.setInputFiles('input[type="file"]', {
    name: `offline-${randomUUID().slice(0, 8)}.synthetic.csv`, mimeType: "text/csv",
    buffer: readFileSync(CSV_PATH),
  });
  await page.getByText(/^Error:/).waitFor({ timeout: 15_000 });
  check("network failure is shown as an error, with no stale verdict or next step",
    (await page.getByText(/^Error:/).isVisible()) &&
    (await page.getByRole("button", { name: "Pilot readiness →" }).count()) === 0 &&
    (await page.locator("main").getByText("server-verified").count()) === 0);
  await page.unroute("**/api/pilot/datasets");

  // ── 10 · Repeating the same upload creates no second governed consequence ───────────────────────
  //
  // THE INVARIANT, read from code rather than assumed:
  //
  //   datasetFingerprint = sha256(csvText)                    src/contract/validateDataset.ts:229
  //   idempotencyKey     = sha256(… , boundaryId, datasetId, datasetFingerprint)            :538-542
  //   prior              = findSubmission(key, boundaryId)         pilotIntakeService.ts:256
  //   prior !== null     -> throw ConflictError("NH-DC-4003: … already submitted on <date>")  -> 409
  //
  // NOTE THE THIRD INPUT. The identity is (boundaryId, datasetId, fingerprint) — NOT boundary + bytes.
  // `datasetId` is the free-text "Dataset label" the uploader types (UploadScreen.tsx:158), so the same
  // bytes re-submitted under a different label are a DIFFERENT identity and are accepted. Checks 6a/6b
  // below measure both halves of that scope rather than describing it. This matters beyond the test:
  // the label is supplied by the party who benefits from the number, which is why it is reported rather
  // than worked around here. Changing the derivation is a constitution question, not a test fix.
  //
  // REFUSE, not reuse: no prior report comes back, the caller gets an error. And `idempotency_key` is
  // the PRIMARY KEY of `pilot_dataset_submissions`, so a second row cannot exist even if that lookup
  // were deleted — the insert would raise P2002 and become a GENERIC 409. Two independent layers,
  // which is why check 3 below pins `NH-DC-4003` specifically rather than "some 409".
  //
  // WHY THIS RUNS HERE. Every other reason this upload could be refused is excluded by placement:
  // CSV_PATH was admitted in section 3, so a prior submission genuinely exists; the bar is ACTIVE and
  // was activated (section 2) BEFORE this dataset was first seen (section 3), so the anti-tuning rule
  // cannot fire; no freeze has happened yet (that is section 11); and the file is the valid fixture.
  // The `NH-DC-4003` assertion then proves it rather than trusting the ordering.
  //
  // NOT PROVABLE HERE: that no second submission ROW was written. No route exposes submissions — the
  // pilot routes are POST /pilot/datasets, the admission-policy and governance routes, and GET/POST
  // /pilot/assessments — and adding one would be a product affordance, not a test. That half rests on
  // the primary key and on `pilotIntake.test.ts` test 5. What the browser CAN show is that no second
  // governed WORK ITEM appeared, which is checked against the server's own execution list.
  const sha256 = (bytes) => createHash("sha256").update(bytes).digest("hex");
  const firstBytes = readFileSync(CSV_PATH);
  const repeatBytes = readFileSync(REPEAT_CSV_PATH);

  // PRECONDITION 1 — the first submission actually succeeded, evidenced by the server's own receipt.
  // Without this the refusal below could be a 409 about a submission that never happened.
  const firstKey = typeof firstIntakeBody?.idempotencyKey === "string" ? firstIntakeBody.idempotencyKey : "";
  check("the first upload was accepted and the server issued an idempotency identity for it",
    firstKey !== "" && firstIntakeBody?.boundaryId === BOUNDARY,
    `key=${firstKey.slice(0, 16)}… boundary=${String(firstIntakeBody?.boundaryId)}`);

  // PRECONDITION 2 — the bytes really are identical. The whole claim is about EXACT byte identity, so
  // this is measured and printed: if a fixture ever changes, this fails loudly instead of the section
  // quietly degrading into "uploading a similar CSV", which would prove nothing about idempotency.
  check("the bytes about to be re-uploaded are byte-identical to the accepted ones",
    sha256(firstBytes) === sha256(repeatBytes) && firstBytes.length === repeatBytes.length,
    `${sha256(firstBytes).slice(0, 16)}… vs ${sha256(repeatBytes).slice(0, 16)}…`);

  // PRECONDITION 3 — how many governed work items exist BEFORE the repeat. Read from the server, so
  // check 5 compares two server readings rather than one reading and an assumption.
  const countExecutions = async () => {
    const res = await page.evaluate(async ([boundaryId, actorId]) => {
      const r = await fetch(`/api/pilot/assessments?boundaryId=${encodeURIComponent(boundaryId)}`, {
        headers: { "x-actor-id": actorId, "x-actor-role": "operator" },
      });
      return { status: r.status, body: r.ok ? await r.json() : await r.text() };
    }, [BOUNDARY, proposerId]);
    return { status: res.status, count: Array.isArray(res.body) ? res.body.length : -1 };
  };
  const before = await countExecutions();
  check("the execution list is readable, so the count below is a real reading and not a default",
    before.status === 200 && before.count >= 1, `status=${before.status} count=${before.count}`);

  // THE REPEAT. Same bytes, same boundary AND the same dataset label — all three inputs of the
  // identity. A fresh label here would silently make this a new submission, and the section would be
  // testing nothing; that is exactly the mistake this run caught on its first attempt.
  await openIntakeScreen(JOURNEY_DATASET_LABEL);
  const repeatReply = page.waitForResponse(
    (r) => r.url().includes("/api/pilot/datasets") && r.request().method() === "POST",
    { timeout: 30_000 },
  );
  await page.setInputFiles('input[type="file"]', REPEAT_CSV_PATH);
  const repeatRes = await repeatReply
    .then(async (r) => ({ status: r.status(), text: await r.text() }))
    .catch(() => ({ status: -1, text: "" }));

  // 3 · From the RESPONSE, not the screen. `NH-DC-4003` is emitted by duplicate detection and by
  // nothing else, so this simultaneously proves the repeat was recognised AND rules out every other
  // refusal reason — frozen policy, anti-tuning, a contract rejection, an authorization refusal.
  check("the repeat is refused 409 and the server names the duplicate-submission code",
    repeatRes.status === 409 && repeatRes.text.includes("NH-DC-4003"),
    `status=${repeatRes.status} body=${repeatRes.text.slice(0, 120)}`);

  // 4 · THE WIRING. `conflict` is in apiClient's SAFE_TO_SHOW_VERBATIM, so the server's own sentence
  // is what the operator reads. No server test can see whether that actually reaches the screen.
  // Asserted with it: no next step is offered, and no stale `server-verified` verdict is left behind —
  // a duplicate shown beside a valid-looking report for the file that was NOT accepted is the failure
  // mode worth having (the NC-15 lesson, on a different path).
  await page.getByText(/^Error:/).waitFor({ timeout: 15_000 }).catch(() => undefined);
  const repeatScreen = (await page.locator("main").innerText()).replace(/\s+/g, " ");
  check("the screen shows the server's duplicate sentence, with no next step and no stale verdict",
    repeatScreen.includes("NH-DC-4003") &&
    repeatScreen.includes("already submitted") &&
    (await page.getByRole("button", { name: "Pilot readiness →" }).count()) === 0 &&
    (await page.locator("main").getByText("server-verified").count()) === 0,
    repeatScreen.slice(0, 160));

  // 5 · The consequence, read back from the server.
  //
  // An upload on its own never creates an execution — only "Run governed execution" does — so a bare
  // count comparison here would be true whatever happened, which is corroboration dressed up as
  // evidence. So where the guard has FAILED and the repeat was admitted, the section follows it
  // through to the governed run, which is where a second work item would actually appear. That is what
  // makes this check able to fail: NC-26 admits the repeat, runs it, and a second execution shows up.
  const repeatAdmitted = (await page.getByRole("button", { name: "Pilot readiness →" }).count()) > 0;
  if (repeatAdmitted) {
    await page.getByRole("button", { name: "Pilot readiness →" }).click();
    await page.getByRole("button", { name: "Observed result →" }).click();
    await page.getByRole("button", { name: "Run governed execution" }).click();
    await page.getByText("Completed — an observation was recorded")
      .waitFor({ timeout: 90_000 }).catch(() => undefined);
  }
  const after = await countExecutions();
  check("repeating the upload created no second governed work item",
    after.status === 200 && after.count === before.count,
    `before=${before.count} after=${after.count} followedThrough=${repeatAdmitted}`);

  // 6 · KEY SCOPE, measured on both movable inputs. These run AFTER the count check above, because
  // each one submits successfully and would otherwise pollute it.
  //
  // Neither is a tenant-isolation claim and neither may be read as one: dev-header actors receive
  // boundaryIds ["*"], so nothing here tests access control. This is key derivation, nothing more.
  const submitOnce = async (label, boundaryId) => {
    await openIntakeScreen(label);
    if (boundaryId !== BOUNDARY) await page.getByLabel("Pilot boundary").fill(boundaryId);
    const reply = page.waitForResponse(
      (r) => r.url().includes("/api/pilot/datasets") && r.request().method() === "POST",
      { timeout: 30_000 },
    );
    await page.setInputFiles('input[type="file"]', REPEAT_CSV_PATH);
    return reply.then(async (r) => ({ status: r.status(), text: await r.text() }))
      .catch(() => ({ status: -1, text: "" }));
  };

  // 6a · THE FINDING. Same bytes, same boundary, a DIFFERENT label — accepted. So "a byte-identical
  // re-upload is refused" is true only while the uploader keeps the label; renaming the dataset defeats
  // duplicate detection. The label is operator-supplied, so this is measured and reported, not fixed
  // here. `NH-DC-4003` asserted ABSENT: it is admitted, not refused for some other reason.
  const relabelled = await submitOnce(`relabelled-${randomUUID().slice(0, 8)}`, BOUNDARY);
  check("the same bytes under a different DATASET LABEL are not a repeat — the label is part of the identity",
    relabelled.status === 200 && !relabelled.text.includes("NH-DC-4003"),
    `status=${relabelled.status}`);

  // 6b · Same bytes, same label, a different boundary — also not a repeat. Together with 6a this shows
  // the refusal above was about this boundary having seen this file under this label, rather than the
  // file being blacklisted anywhere it appears.
  const elsewhere = await submitOnce(JOURNEY_DATASET_LABEL, `${BOUNDARY}-elsewhere`);
  check("the same bytes under a different boundary are not a repeat — the identity is boundary-scoped",
    elsewhere.status === 200 && !elsewhere.text.includes("NH-DC-4003"),
    `status=${elsewhere.status}`);

  // ── 11 · A frozen bar stops judging, and freezing is not decorative ─────────────────────────────
  //
  // WHAT IS PROVABLE HERE, AND WHAT IS NOT. The server enforces the frozen state in TWO independent
  // places: at intake (`pilotIntakeService.ts`, which refuses admission) and again at schedule time
  // (`pilotAssessmentService.ts`, `NH-AX-1007 policy_not_active`, re-checked on a dataset admitted
  // while the bar was still ACTIVE). Only the first is reachable from this UI. `App.tsx` renders
  // screens conditionally, so going to the governance screen UNMOUNTS `Assessment` and discards the
  // admitted dataset; on return the same file is refused earlier, at intake. A browser test aimed at
  // the schedule-time rule would therefore observe the intake refusal and credit it to the wrong
  // rule — so it is not attempted. That rule stays covered at service level.
  //
  // This runs last of the data sections deliberately: everything above needs the bar ACTIVE, and
  // section 9's refusal has to stay a TRANSPORT refusal rather than a governance one.
  const readLifecycle = async () => {
    await page.goto(UI_BASE, { waitUntil: "domcontentloaded" });
    await page.getByRole("button", { name: "Pilot Policy Governance" }).click();
    await page.getByLabel("Boundary (tenant)").fill(BOUNDARY);
    await page.getByLabel("Policy id").fill(POLICY_ID);
    await page.getByLabel("Policy version").fill(POLICY_VERSION);
    await page.getByLabel("Rationale (required on every act)").fill("journey freeze/resume");
    await page.getByRole("button", { name: "Read lifecycle" }).click();
  };

  // Scoped to the lifecycle panel, NOT the page: `FROZEN` is both a state and a transition, so it
  // appears in the state pill AND in the audit trail below. An unscoped `getByText("FROZEN")` resolves
  // two elements and Playwright's strict mode throws — and a `.first()` would be a guess about which.
  const lifecycle = () => page.getByText("3 · Lifecycle", { exact: true }).locator("..");

  await readLifecycle();
  // PRECONDITION. Every check below describes a transition away from ACTIVE, so if the lifecycle read
  // did not land the section would be asserting against a blank screen. Nothing here may pass on one.
  await lifecycle().getByText("ACTIVE", { exact: true }).waitFor({ timeout: 15_000 }).catch(() => undefined);
  const wasActive = (await lifecycle().getByText("ACTIVE", { exact: true }).isVisible()) &&
    (await lifecycle().getByText("may judge a dataset").isVisible());
  check("the bar this journey has been judging against is ACTIVE before it is frozen", wasActive);
  haltIf(!wasActive, "the bar was not ACTIVE before the freeze, so a later FROZEN reading would not " +
    "show that freezing changed anything");

  await page.getByRole("button", { name: "Freeze" }).click();
  await lifecycle().getByText("FROZEN", { exact: true }).waitFor({ timeout: 15_000 }).catch(() => undefined);
  // The state, the verdict and the guidance together. The verdict is the one that matters: a pill
  // reading FROZEN beside "may judge a dataset" would be a screen contradicting itself.
  check("a frozen bar reads FROZEN and judges nothing",
    (await lifecycle().getByText("FROZEN", { exact: true }).isVisible()) &&
    (await lifecycle().getByText("judges nothing").isVisible()) &&
    !(await lifecycle().getByText("may judge a dataset").count()) &&
    (await page.getByText("Paused by pilot governance. It judges nothing until it is resumed.").isVisible()));

  // Scoped to the audit panel, as sections 1-2 are — the server's append-only record, not the buttons.
  const frozenAudit = ((await page.getByText("Who decided what", { exact: false }).locator("..")
    .innerText().catch(() => "")) || "").replace(/\s+/g, " ");
  check("the audit trail records the FROZEN transition against the steward who made it",
    frozenAudit.includes("FROZEN") && frozenAudit.includes(bareId(stewardName)),
    frozenAudit.slice(-160));

  // Everything below needs the bar to be FROZEN. If the freeze was refused the bar is still ACTIVE, so
  // the dataset is ADMITTED, the flow leaves Upload on its own and the report panel unmounts — the
  // "frozen refusal" checks would then be waiting for a panel that cannot appear. NC-21 lands exactly
  // there, so the run stops here with the cause already recorded above rather than spending a timeout.
  const isFrozen = await lifecycle().getByText("FROZEN", { exact: true }).isVisible();
  haltIf(!isFrozen, "the bar is not FROZEN, so there is no frozen state for an intake refusal to come " +
    "from and an admitted dataset would leave the upload screen instead");

  // THE OUTCOME CHECK. A state pill is a claim about governance; this is whether governance bites.
  await openIntakeScreen(`frozen-${randomUUID().slice(0, 8)}`);
  const frozenReply = page.waitForResponse(
    (r) => r.url().includes("/api/pilot/datasets") && r.request().method() === "POST",
    { timeout: 30_000 },
  );
  await page.setInputFiles('input[type="file"]', FROZEN_CSV_PATH);
  // Degrading, not throwing. If the frozen state stops being enforced the dataset is ADMITTED, the flow
  // leaves Upload on its own and this panel unmounts — so a bare wait would abort the run and report
  // `65/65 recorded checks passed` with the refusal check never printed. NC-22 lands exactly there, and
  // the failure has to be attributable to the named check below, not to a timeout.
  await page.getByText("Data contract validation", { exact: true })
    .waitFor({ timeout: 30_000 }).catch(() => undefined);
  const frozenBody = await frozenReply.then((r) => (r.ok() ? r.json() : null)).catch(() => null);
  const frozenText = (await page.locator("main").innerText()).replace(/\s+/g, " ");
  // Two checks, not one, so the controls are distinguishable. Removing the intake gate (NC-22) admits
  // the dataset and unmounts the panel, failing BOTH. Breaking only the state label (NC-23) leaves the
  // refusal intact and fails only the second — which is the difference between "governance stopped it"
  // and "the operator can see what stopped it".
  //
  // `server-verified` matters: this is the server refusing admission, NOT the local preflight path.
  // Reading a preflight refusal as a governance refusal is the mistake `cc9029e` made in reverse.
  check("a frozen bar refuses the dataset at intake and keeps it on the upload screen",
    frozenText.includes("server-verified") &&
    frozenText.includes("the policy is frozen by pilot governance and may not judge new datasets") &&
    (await page.getByRole("button", { name: "Pilot readiness →" }).count()) === 0);
  check("the refusal names WHICH lifecycle state stopped it, not merely that something did",
    frozenText.includes("frozen by governance"));
  // The server's payload, not the screen's wording — the two must agree about which state refused.
  check("the server reported the frozen state for that refusal",
    frozenBody?.admissionPolicyState === "FROZEN",
    `admissionPolicyState=${String(frozenBody?.admissionPolicyState)}`);

  // Resuming. ONLY the state round-trip is asserted: `policyGovernanceState` takes the LATEST
  // activation (ACTIVATED or UNFROZEN) as `activatedAt`, so after a resume the anti-tuning rule
  // (`activatedAt > firstSeenAt`) correctly refuses any dataset first seen before it. "It judges
  // again" is therefore FALSE for every dataset this run has already submitted, and no check here
  // claims otherwise — that is a pre-registration rule, not a frozen-policy one.
  await readLifecycle();
  await lifecycle().getByText("FROZEN", { exact: true }).waitFor({ timeout: 15_000 }).catch(() => undefined);
  // The button is labelled "Resume"; the TRANSITION it records is `UNFROZEN`. Asserting the screen's
  // word and the server's word separately is deliberate — they are allowed to differ, and the audit
  // check below is against the server's.
  await page.getByRole("button", { name: "Resume" }).click();
  await lifecycle().getByText("ACTIVE", { exact: true }).waitFor({ timeout: 15_000 }).catch(() => undefined);
  check("resuming a frozen bar restores ACTIVE and its authority to judge",
    (await lifecycle().getByText("ACTIVE", { exact: true }).isVisible()) &&
    (await lifecycle().getByText("may judge a dataset").isVisible()) &&
    !(await lifecycle().getByText("judges nothing").count()));
  const resumedAudit = ((await page.getByText("Who decided what", { exact: false }).locator("..")
    .innerText().catch(() => "")) || "").replace(/\s+/g, " ");
  check("the audit trail records the resume as its own act, leaving the freeze in place",
    resumedAudit.includes("UNFROZEN") && resumedAudit.includes("FROZEN") &&
    resumedAudit.includes(bareId(stewardName)),
    resumedAudit.slice(-160));

  // ── 12 · Egress and page health ──────────────────────────────────────────────────────────────────
  const external = requested.filter((u) => !u.startsWith(UI_BASE) && !u.startsWith("data:") && !u.startsWith("blob:"));
  check("the page made no request outside its own origin", external.length === 0, external.slice(0, 3).join(", "));
  check("no uncaught page error occurred", pageErrors.length === 0, pageErrors.slice(0, 2).join(" | "));
} catch (error) {
  if (error instanceof JourneyHalted) {
    // Not a harness error: a stop this harness asked for, after recording why. `failures` is already
    // non-zero (haltIf guarantees it), so the run still reports FAILED — it just reports it truthfully.
    halted = error.message;
    console.error(`HALTED · ${error.message}`);
  } else {
    failures += 1;
    console.error(`FAIL · harness error · ${error instanceof Error ? error.stack : String(error)}`);
  }
} finally {
  if (browser) await browser.close().catch(() => undefined);
  stop(ui);
  stop(api);
}

// The summary has to be unmistakable in a CI log. A harness error (a timeout, a missing element)
// is not a recorded check, so printing only "n/n checks passed" would read as a pass on a run that
// never reached most of its assertions — which is exactly what happens when the governed wiring
// regresses: the journey dies at the upload screen having passed every check before it.
const passed = results.filter((r) => r.ok).length;
const unrecorded = failures - results.filter((r) => !r.ok).length;
console.log(`\n${passed}/${results.length} recorded checks passed`);
if (unrecorded > 0) {
  console.log(`${unrecorded} harness error(s) — the journey did not finish, so the checks after the`);
  console.log("failure point never ran. This is a FAILURE, not a partial pass.");
}
if (halted) {
  console.log(`HALTED after the recorded failure above: ${halted}.`);
  console.log("The remaining steps were structurally unreachable, so they never ran and are NOT");
  console.log("counted as passes. This is a FAILURE, not a partial pass.");
}
console.log(failures === 0 ? "JOURNEY PASSED" : `JOURNEY FAILED (${failures} problem(s))`);
process.exit(failures === 0 ? 0 : 1);
