// EP-19 · The complete pilot journey, in a real browser, against the real API, worker and database.
//
// WHAT THIS PROVES that no in-process test can: that the screens a pilot actually touches reach a
// governed server finding, and that the figure on the final screen is the SERVER's number rather
// than something the browser worked out for itself. Those two claims are the product.
//
// Three things make this harness different from `e2e/smoke.mjs`:
//
//   1. It uses the Vite DEV server, not `vite preview`. `apiClient.ts` attaches development identity
//      headers only when `import.meta.env.DEV`, so against a production build every governed call
//      would arrive unauthenticated and 401. A preview-based harness could not reach the API at all.
//   2. It starts a real Fastify process with a real worker loop over a real PostgreSQL database.
//   3. The two governance halves are performed by two DIFFERENT identities, because the server
//      refuses them from one — which is the point of the separation, not a detail of the screen.
//
// Deterministic: a fixed synthetic CSV, a fixed as-of date, a boundary derived once per run.
// Exits non-zero on any failure. Never uses real or disguised customer data.
import { chromium } from "playwright";
import { spawn } from "node:child_process";
import { existsSync, readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve, join } from "node:path";
import { randomUUID } from "node:crypto";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const API_PORT = Number(process.env.JOURNEY_API_PORT ?? 4000);
const UI_PORT = Number(process.env.JOURNEY_UI_PORT ?? 5199);
const UI_BASE = `http://127.0.0.1:${UI_PORT}/`;
const CHROMIUM = "/opt/pw-browsers/chromium";
const executablePath = existsSync(CHROMIUM) ? CHROMIUM : undefined;

if (!process.env.DATABASE_URL) {
  console.error("DATABASE_URL is required — this harness runs against a real database on purpose.");
  process.exit(2);
}

// One boundary per run. The worker polls a fixed boundary list, so it has to be known before the
// server starts; deriving it here (rather than hardcoding) keeps repeat runs from colliding.
const BOUNDARY = `journey-${randomUUID().slice(0, 8)}`;
const POLICY_ID = `journey-bar-${randomUUID().slice(0, 8)}`;
const POLICY_VERSION = "1.0.0";
const AS_OF = "2026-03-01";

const results = [];
let failures = 0;
function check(name, ok, detail = "") {
  results.push({ name, ok });
  if (!ok) failures += 1;
  console.log(`${ok ? "PASS" : "FAIL"} · ${name}${detail ? ` · ${detail}` : ""}`);
}
function checkEqual(name, actual, expected) {
  check(name, actual === expected, actual === expected ? "" : `expected ${expected}, got ${actual}`);
}

// ── Fixture ────────────────────────────────────────────────────────────────────────────────────────
// Generated by the repository's own deterministic generator, so the browser journey and the server
// matrix are exercising the same bytes. Written to a temp file because the screen takes a file pick.
// `npm run test:journey` writes these first, via `scripts/write-journey-fixture.ts`, so the bytes
// come from the same generator the server matrix uses rather than a copy pasted in here.
const CSV_PATH = join(ROOT, "e2e/fixtures/journey.synthetic.csv");
if (!existsSync(CSV_PATH)) {
  console.error("missing journey fixture — run `npm run fixture:journey` first (test:journey does).");
  process.exit(2);
}
const { policy: SCENARIO_POLICY, scenarios: RISK_SCENARIOS } = JSON.parse(
  readFileSync(join(ROOT, "e2e/fixtures/journey.fixture.json"), "utf8"),
);

// ── Processes ──────────────────────────────────────────────────────────────────────────────────────
function startProcess(label, command, args, env) {
  const child = spawn(command, args, {
    cwd: ROOT,
    detached: true,
    env: { ...process.env, ...env },
    stdio: ["ignore", "pipe", "pipe"],
  });
  child.stdout.on("data", (b) => process.env.JOURNEY_VERBOSE && console.log(`[${label}] ${b}`));
  child.stderr.on("data", (b) => console.error(`[${label}] ${b}`));
  return child;
}

function startApi() {
  return startProcess("api", process.execPath, [resolve(ROOT, "node_modules/.bin/vite-node"), "server/index.ts"], {
    PORT: String(API_PORT),
    HOST: "127.0.0.1",
    // The worker must be running for an execution to leave `queued`.
    NH_AGENTS_ENABLED: "true",
    NH_AGENT_BOUNDARIES: BOUNDARY,
    NH_AGENT_IDLE_DELAY_MS: "200",
    // EP-18: the assessment agent publishes no candidates, so it needs no admission-policy registry.
    // Supplying a fabricated RecoveryType:threshold pair here would put an invented number into the
    // configuration of a test whose whole subject is not inventing numbers.
    NH_PILOT_ASSESSMENT_AGENT_ENABLED: "true",
    NH_PILOT_INPUT_TERMINAL_GRACE_HOURS: "24",
    NH_PILOT_INPUT_ABANDONED_RETENTION_DAYS: "7",
  });
}

function startUi() {
  return startProcess("ui", process.execPath, [
    resolve(ROOT, "node_modules/vite/bin/vite.js"),
    "--port", String(UI_PORT), "--strictPort", "--host", "127.0.0.1",
  ], { API_PORT: String(API_PORT) });
}

async function waitFor(label, probe, timeoutMs = 60_000) {
  const deadline = Date.now() + timeoutMs;
  let last = "";
  while (Date.now() < deadline) {
    try {
      if (await probe()) return;
    } catch (e) {
      last = e instanceof Error ? e.message : String(e);
    }
    await new Promise((r) => setTimeout(r, 400));
  }
  throw new Error(`${label} did not become reachable within ${timeoutMs}ms${last ? ` (${last})` : ""}`);
}

function stop(child) {
  if (!child?.pid) return;
  try { process.kill(-child.pid, "SIGTERM"); } catch { /* already gone */ }
}

// ── The journey ────────────────────────────────────────────────────────────────────────────────────
let api, ui, browser;
try {
  api = startApi();
  ui = startUi();
  await waitFor("api", async () => (await fetch(`http://127.0.0.1:${API_PORT}/health`)).ok);
  await waitFor("ui", async () => (await fetch(UI_BASE)).ok);

  browser = await chromium.launch({ executablePath });
  const context = await browser.newContext();
  const page = await context.newPage();

  // Every request the page makes, so "no external egress" is a measured claim, not an assumption.
  const requested = [];
  page.on("request", (r) => requested.push(r.url()));
  const pageErrors = [];
  page.on("pageerror", (e) => pageErrors.push(e.message));

  await page.goto(UI_BASE, { waitUntil: "domcontentloaded" });

  // ── 1 · Governance: the operator proposes the bar ────────────────────────────────────────────────
  await page.getByRole("button", { name: "Pilot Policy Governance" }).click();
  await page.getByLabel("Boundary (tenant)").fill(BOUNDARY);
  await page.getByLabel("Policy id").fill(POLICY_ID);
  await page.getByLabel("Policy version").fill(POLICY_VERSION);
  for (const [label, value] of [
    ["Min accepted rows", String(SCENARIO_POLICY.minAcceptedRows)],
    ["Min distinct entities", String(SCENARIO_POLICY.minDistinctEntities)],
    ["Min coverage (days)", String(SCENARIO_POLICY.minCoverageDays)],
    ["Max missing recommended cols", String(SCENARIO_POLICY.maxMissingRecommendedColumns)],
    ["Max rejection rate", String(SCENARIO_POLICY.maxRejectionRate)],
    ["Max single-reason share", String(SCENARIO_POLICY.maxSingleReasonShare)],
    ["Max duplicate rate", String(SCENARIO_POLICY.maxDuplicateRate)],
    ["Max ordering-defect rate", String(SCENARIO_POLICY.maxOrderingDefectRate)],
  ]) {
    await page.getByLabel(label, { exact: true }).fill(value);
  }
  // The review gate first: the three state boxes are disabled until it is ticked, so an untouched form
  // cannot half-state a policy.
  await page.getByLabel("I have reviewed lifecycle coverage").check();
  for (const state of SCENARIO_POLICY.requiredLifecycleStates) {
    await page.getByRole("group", { name: "Required lifecycle states" }).getByLabel(state, { exact: true }).check();
  }
  await page.getByLabel("Require provenance declaration").selectOption(String(SCENARIO_POLICY.requireProvenanceDeclaration));
  await page.getByLabel("Rationale (required on every act)").fill("journey fixture bar");

  const proposeButton = page.getByRole("button", { name: /^Propose as / });
  const activateButton = page.getByRole("button", { name: /^Activate as / });

  // An out-of-range threshold must NAME the field. A silently disabled button sends an operator hunting
  // through eight boxes, and `validateAdmissionPolicy` already returns the field and the reason.
  await page.getByLabel("Max duplicate rate", { exact: true }).fill("1.1");
  const defect = page.getByLabel("Policy threshold errors").getByText(/maxDuplicateRate:.*between 0 and 1/);
  // waitFor before sampling: isVisible() reads the DOM as it is right now, so a check that ran before
  // React flushed would report the defect list missing when it had merely not rendered yet. A false
  // FAIL here is noise; the same race in the other direction is how a real gap gets a green tick.
  await defect.waitFor({ state: "visible", timeout: 10_000 }).catch(() => undefined);
  check("an invalid threshold names the field and blocks proposal",
    (await defect.isVisible()) && !(await proposeButton.isEnabled()));
  await page.getByLabel("Max duplicate rate", { exact: true }).fill(String(SCENARIO_POLICY.maxDuplicateRate));
  const proposerName = (await proposeButton.textContent())?.replace("Propose as ", "").trim() ?? "";
  const stewardName = (await activateButton.textContent())?.replace("Activate as ", "").trim() ?? "";
  check(
    "the two governance acts are offered as two different identities",
    proposerName !== "" && stewardName !== "" && proposerName !== stewardName,
    `${proposerName} vs ${stewardName}`,
  );

  await proposeButton.click();
  await page.getByText("DRAFT", { exact: true }).waitFor({ timeout: 15_000 });
  check("a proposed bar is DRAFT and judges nothing", await page.getByText("judges nothing").isVisible());

  // ── 2 · Governance: a DIFFERENT identity puts it in force ────────────────────────────────────────
  await activateButton.click();
  await page.getByText("ACTIVE", { exact: true }).waitFor({ timeout: 15_000 });
  check("an activated bar may judge a dataset", await page.getByText("may judge a dataset").isVisible());

  // A lifecycle belongs to one exact boundary, policy id and version. Editing any of them must
  // immediately hide the old ACTIVE verdict — the state, the "may judge" pill and the hash together.
  const policyIdInput = page.getByLabel("Policy id", { exact: true });
  await policyIdInput.fill(`${POLICY_ID}-other`);
  check("changing policy identity hides the old ACTIVE verdict",
    (await page.getByText("not proposed", { exact: true }).isVisible()) &&
    !(await page.getByText("may judge a dataset").count()) &&
    !(await page.getByText("Policy hash", { exact: false }).count()));
  // Restoring the identity does NOT restore the verdict: it has to be read again, deliberately.
  await policyIdInput.fill(POLICY_ID);
  check("restoring the identity still requires an explicit re-read",
    await page.getByText("not proposed", { exact: true }).isVisible());
  await page.getByRole("button", { name: "Read lifecycle" }).click();
  await page.getByText("ACTIVE", { exact: true }).waitFor({ timeout: 15_000 });

  // The screen must show both halves attributed to their own actor — the audit claim, on screen.
  const governanceText = await page.locator("main").innerText();
  check(
    "the lifecycle names the proposer and the activator separately",
    governanceText.includes(proposerName) && governanceText.includes(stewardName),
  );

  // ── 3 · Assessment: intake and admission ────────────────────────────────────────────────────────
  await page.getByRole("button", { name: "Revenue Opportunity Assessment" }).click();
  await page.getByLabel("Admission policy id").fill(POLICY_ID);
  await page.getByLabel("Admission policy version").fill(POLICY_VERSION);
  await page.getByLabel("Analysis as-of date").fill(AS_OF);
  await page.getByLabel("Pilot boundary").fill(BOUNDARY);
  await page.getByLabel("Dataset label").fill(`journey-${randomUUID().slice(0, 8)}`);
  await page.getByLabel("Contract system of record").fill("synthetic-crm");
  await page.getByLabel("Billing system of record").fill("synthetic-billing");
  await page.getByLabel("Product/telemetry source").fill("synthetic-telemetry");
  await page.getByLabel("Data owner (role, not a person)").fill("synthetic-revenue-operations");
  await page.getByLabel("Extraction method").fill("synthetic deterministic generator");
  await page.getByLabel("Extracted at (UTC)").fill("2026-03-01T00:00:00.000Z");
  await page.getByLabel("Coverage start").fill("2026-01-01");
  await page.getByLabel("Coverage end").fill("2026-03-31");

  await page.setInputFiles('input[type="file"]', CSV_PATH);

  // Admitted ⇒ the flow leaves Upload on its own. Before EP-19 it could not, because the UI never
  // sent an admission policy id and the server therefore always answered NOT_ASSESSABLE.
  await page.getByRole("button", { name: "Pilot readiness →" }).waitFor({ timeout: 30_000 });
  check("an admitted dataset leaves the upload screen", true);

  // ── 4 · The browser's own figure is reachable, and is labelled a preview ─────────────────────────
  await page.getByRole("button", { name: "Pilot readiness →" }).click();
  await page.getByRole("button", { name: "Observed result →" }).click();
  const previewText = await page.locator("main").innerText();
  check(
    "the browser figure says it was computed in this browser",
    /local preview/i.test(previewText) && /in this browser/i.test(previewText),
  );
  check(
    "the browser figure denies being an execution, a Proof or Revenue Returned",
    /not an execution, a Proof, or Revenue Returned/i.test(previewText.replace(/\s+/g, " ")),
  );

  // ── 5 · The governed execution ───────────────────────────────────────────────────────────────────
  await page.getByRole("button", { name: "Run governed execution" }).click();

  // `completed` is the only acceptable end. A timeout here is a failure of the journey, not a pass:
  // the screen is required to show a timeout as a timeout, and this harness is required to fail.
  // The execution-state pill, specifically — the event log below it also contains the word, and
  // matching either would let a COMPLETED event on a run that is still settling read as a result.
  await page.getByText("Completed — an observation was recorded").waitFor({ timeout: 90_000 });
  // Scoped to <main>, NOT the whole body. The sidebar carries a standing "Auditable recovered"
  // total for the separate proven ledger — that belongs there, and matching it would turn correct
  // two-ledger chrome into a false failure while hiding a real one in the noise.
  const executionText = (await page.locator("main").innerText()).replace(/\s+/g, " ");
  check(
    "the governed execution reached a server-reported completion",
    /Completed — an observation was recorded/.test(executionText),
  );

  // ── 6 · The displayed figures are the SERVER's, not the browser's ────────────────────────────────
  const proposerId = proposerName.replace(/\s*\(.*\)$/, "").trim();
  const listed = await page.evaluate(async ([boundaryId, actorId]) => {
    const res = await fetch(`/api/pilot/assessments?boundaryId=${encodeURIComponent(boundaryId)}`, {
      headers: { "x-actor-id": actorId, "x-actor-role": "operator" },
    });
    // Surfaced rather than swallowed: an unauthorised read must not be indistinguishable from a
    // boundary that genuinely holds no execution.
    return { status: res.status, body: res.ok ? await res.json() : await res.text() };
  }, [BOUNDARY, proposerId]);
  checkEqual("the execution list is readable by the acting operator", listed.status, 200);
  // The endpoint returns a bare array, not a wrapper object.
  const executions = Array.isArray(listed.body) ? listed.body : [];
  const executionId = executions[0]?.executionId ?? null;
  check("exactly one execution exists for this boundary", executions.length === 1,
    `status=${listed.status} count=${executions.length}`);

  const apiView = executionId
    ? await page.evaluate(async ([boundaryId, id, actorId]) => {
        const res = await fetch(
          `/api/pilot/assessments/${id}?boundaryId=${encodeURIComponent(boundaryId)}`,
          { headers: { "x-actor-id": actorId, "x-actor-role": "operator" } },
        );
        return res.ok ? res.json() : null;
      }, [BOUNDARY, executionId, proposerId])
    : null;

  checkEqual("the API agrees the execution completed", apiView?.state, "completed");
  const finding = apiView?.finding?.finding ?? null;
  check("the API produced a finding", finding !== null);
  if (finding) {
    // The load-bearing comparison of the whole harness: the number on the screen is the number the
    // server computed. A browser-side figure that merely happened to look plausible would fail here.
    check(
      `the screen shows the server's cycle count (${finding.acceptedCycleCount})`,
      executionText.includes(String(finding.acceptedCycleCount)),
    );
    const minorToText = (minor) =>
      (minor / 100).toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 });
    check(
      `the screen shows the server's observed unpaid amount (${minorToText(finding.observedUnpaidMinor)})`,
      executionText.includes(minorToText(finding.observedUnpaidMinor)),
    );
    check("the execution is bound to an admission decision", Boolean(apiView.binding?.admissionDecisionId));
  }

  // ── 7 · Nothing on the result claims proven money ────────────────────────────────────────────────
  //
  // Banning the words outright would be the wrong test: this panel SHOULD say "no dollar here has
  // been recovered, proven, or counted", and a check that failed on that would push the honest
  // sentence off the screen. So the rule is the repository's existing one for retracted claims —
  // the proven-ledger vocabulary may appear only inside a denial of itself.
  const NEGATION = /\b(no|not|never|nothing|without)\b/i;
  for (const term of ["Revenue Returned", "Auditable", "recovered", "proven"]) {
    const pattern = new RegExp(`(.{0,60})\\b${term}\\b`, "gi");
    const claims = [];
    for (const match of executionText.matchAll(pattern)) {
      if (!NEGATION.test(match[1] ?? "")) claims.push(`…${match[1]}${term}`);
    }
    check(
      `the governed result mentions "${term}" only to deny it`,
      claims.length === 0,
      claims.slice(0, 2).join(" | "),
    );
  }
  // And the denial must actually be present, not merely un-contradicted: an empty panel would pass
  // every check above while telling the reader nothing about what the figure is not.
  check(
    "the governed result states plainly that nothing here was recovered, proven or counted",
    /no dollar here has been recovered, proven, or counted/i.test(executionText),
  );
  check(
    "the governed result names itself Revenue Opportunity",
    /Revenue Opportunity/i.test(executionText),
  );

  // ── 8 · Each generated data-risk scenario, through the actual upload screen ────────────────────
  // The API/worker matrix checks the domain decision. These checks also catch a browser that shows
  // a misleading verdict, promotes a preflight refusal to a server verdict, or lets a refused
  // dataset leave Upload. Each file gets a fresh screen and dataset id; all share the activated bar.
  /**
   * What the report panel SHOWS, asserted identically whether the dataset was admitted or refused.
   *
   * One helper rather than two copies: a dataset can be correctly admitted by the server and still be
   * displayed with the wrong counts, or with a rejected row's code silently dropped. That is the class
   * of defect only a browser can see, and it is no less serious on the admitted path.
   */
  /**
   * The number a Counter shows, compared EXACTLY.
   *
   * Not `endsWith`: a counter displaying 31 where 1 is expected ends with "1" and would pass. NC-12
   * caught that — sabotaging the panel to show `dataRows` left `one-valid-row` green, because its
   * expected accepted count is 1 and the wrong value was 31. The value is the counter's last token,
   * with the thousands separator `toLocaleString` adds removed.
   */
  function counterValue(text) {
    const last = text.trim().split(/\s+/).pop() ?? "";
    return Number(last.replace(/,/g, ""));
  }

  async function checkVisibleReport(scenario) {
    const report = page.locator("main");
    const accepted = await page.getByText("Accepted", { exact: true }).locator("..").innerText();
    const rejected = await page.getByText("Rejected", { exact: true }).locator("..").innerText();
    check(`${scenario.id}: the visible accepted/rejected counts match the fixture`,
      counterValue(accepted) === scenario.expected.acceptedRows &&
      counterValue(rejected) === scenario.expected.rejectedRows,
      `accepted=${counterValue(accepted)} rejected=${counterValue(rejected)} ` +
      `expected ${scenario.expected.acceptedRows}/${scenario.expected.rejectedRows}`);
    for (const code of scenario.expected.codes) {
      check(`${scenario.id}: the report names ${code}`,
        (await report.getByText(code, { exact: true }).count()) > 0);
    }
  }

  for (const scenario of RISK_SCENARIOS) {
    await page.goto(UI_BASE, { waitUntil: "domcontentloaded" });
    await page.getByRole("button", { name: "Revenue Opportunity Assessment" }).click();
    await page.getByLabel("Admission policy id").fill(POLICY_ID);
    await page.getByLabel("Admission policy version").fill(POLICY_VERSION);
    await page.getByLabel("Analysis as-of date").fill(AS_OF);
    await page.getByLabel("Pilot boundary").fill(BOUNDARY);
    await page.getByLabel("Dataset label").fill(`matrix-${scenario.id}-${randomUUID().slice(0, 8)}`);
    await page.getByLabel("Contract system of record").fill("synthetic-crm");
    await page.getByLabel("Billing system of record").fill("synthetic-billing");
    await page.getByLabel("Product/telemetry source").fill("synthetic-telemetry");
    await page.getByLabel("Data owner (role, not a person)").fill("synthetic-revenue-operations");
    await page.getByLabel("Extraction method").fill("synthetic deterministic generator");
    await page.getByLabel("Extracted at (UTC)").fill("2026-03-01T00:00:00.000Z");
    await page.getByLabel("Coverage start").fill("2026-01-01");
    await page.getByLabel("Coverage end").fill("2026-03-31");

    const serverReply = scenario.expected.usableForAssessment
      ? page.waitForResponse(
          (r) => r.url().includes("/api/pilot/datasets") && r.request().method() === "POST",
          { timeout: 30_000 },
        )
      : null;
    await page.setInputFiles('input[type="file"]', {
      name: `${scenario.id}.synthetic.csv`, mimeType: "text/csv",
      buffer: Buffer.from(scenario.csvText, "utf8"),
    });

    if (scenario.expected.admission === "ADMISSIBLE") {
      await page.getByRole("button", { name: "Pilot readiness →" }).waitFor({ timeout: 30_000 });
      const reply = await serverReply;
      const body = reply?.ok() ? await reply.json() : null;
      check(`${scenario.id}: admitted by the server and progressed in the browser`,
        body?.admission?.outcome === "ADMISSIBLE" &&
        body.counts?.acceptedRows === scenario.expected.acceptedRows &&
        body.counts?.rejectedRows === scenario.expected.rejectedRows);

      // The report panel is NOT on screen here: progressing moved the flow to the cohort step, which
      // unmounts it. `validation` survives that move (it is cleared only by the next upload), so going
      // back to Upload re-renders the panel with the SERVER result — deterministically, no race.
      await page.getByRole("button", { name: "← Upload" }).click();
      await page.getByText("Data contract validation", { exact: true }).waitFor({ timeout: 30_000 });
      check(`${scenario.id}: the admitted report is marked server-verified`,
        (await page.locator("main").innerText()).includes("server-verified"));
      await checkVisibleReport(scenario);
    } else {
      await page.getByText("Data contract validation", { exact: true }).waitFor({ timeout: 30_000 });
      const admissionPill = page.getByText("Pilot admission", { exact: true }).locator("..");
      const preliminary = !scenario.expected.usableForAssessment;
      if (preliminary) {
        // A local preflight evaluates admission with NO policy, so its pill reads "not assessable" for
        // every unusable dataset whatever its real fitness would be — asserting that it equals the
        // fixture's admission would prove nothing. What the preview actually means is that no bar was
        // applied, and the panel says so. This fails if the browser ever shows a fitness verdict it
        // cannot know, which is the only thing worth checking here.
        await admissionPill.getByText("no policy configured", { exact: true }).waitFor({ timeout: 30_000 });
      } else {
        await admissionPill.getByText(scenario.expected.admission.replace(/_/g, " ").toLowerCase(),
          { exact: true }).waitFor({ timeout: 30_000 });
      }
      const reply = await serverReply;
      if (!preliminary && !reply) throw new Error(`${scenario.id}: expected server verdict, got no response`);
      // An unusable file stops at local preflight and is labelled as such; a usable but unfit file
      // must receive an authoritative server verdict. Neither may expose the next-step button.
      const report = page.locator("main");
      const text = await report.innerText();
      check(`${scenario.id}: refusal has the correct authority and remains on Upload`,
        text.includes(preliminary ? "preview — not yet confirmed by the server" : "server-verified") &&
        (await page.getByRole("button", { name: "Pilot readiness →" }).count()) === 0);
      await checkVisibleReport(scenario);
      if (reply) {
        const body = await reply.json();
        check(`${scenario.id}: browser refusal agrees with the server`,
          body.admission?.outcome === scenario.expected.admission &&
          body.counts?.acceptedRows === scenario.expected.acceptedRows &&
          body.counts?.rejectedRows === scenario.expected.rejectedRows);
      }
    }
  }

  // ── 9 · Egress and page health ───────────────────────────────────────────────────────────────────
  const external = requested.filter((u) => !u.startsWith(UI_BASE) && !u.startsWith("data:") && !u.startsWith("blob:"));
  check("the page made no request outside its own origin", external.length === 0, external.slice(0, 3).join(", "));
  check("no uncaught page error occurred", pageErrors.length === 0, pageErrors.slice(0, 2).join(" | "));
} catch (error) {
  failures += 1;
  console.error(`FAIL · harness error · ${error instanceof Error ? error.stack : String(error)}`);
} finally {
  if (browser) await browser.close().catch(() => undefined);
  stop(ui);
  stop(api);
}

// The summary has to be unmistakable in a CI log. A harness error (a timeout, a missing element)
// is not a recorded check, so printing only "n/n checks passed" would read as a pass on a run that
// never reached most of its assertions — which is exactly what happens when the governed wiring
// regresses: the journey dies at the upload screen having passed every check before it.
const passed = results.filter((r) => r.ok).length;
const unrecorded = failures - results.filter((r) => !r.ok).length;
console.log(`\n${passed}/${results.length} recorded checks passed`);
if (unrecorded > 0) {
  console.log(`${unrecorded} harness error(s) — the journey did not finish, so the checks after the`);
  console.log("failure point never ran. This is a FAILURE, not a partial pass.");
}
console.log(failures === 0 ? "JOURNEY PASSED" : `JOURNEY FAILED (${failures} problem(s))`);
process.exit(failures === 0 ? 0 : 1);
